In [ ]:
# Hello, Lests start py

In [1]:
print("Hello World")

Hello World


In [2]:
import sys
sys.version

'3.13.15 (main, Aug  6 2026, 11:06:23) [GCC 11.4.0]'

In [3]:
num =5
square = num * num
print(square)

25


In [4]:
1abc = "hello"
print(1abc)

SyntaxError: invalid decimal literal (2056252767.py, line 1)

In [5]:
abc = "hello"
print(abc)

hello


In [6]:
_abc = "hello"
print(abc)

hello


In [7]:
# datatype
x = 2
print(x)
print(type(x))

2
<class 'int'>


In [8]:
y = 2.5
print(y)
print(type(y))

2.5
<class 'float'>


In [10]:
x = "amrit"
print(x)
print(type(x))

amrit
<class 'str'>


In [11]:
x = 2 + 3j
print(x)
print(type(x))

(2+3j)
<class 'complex'>


In [12]:
x = (1,2,3)
print(x)
print(type(x))

(1, 2, 3)
<class 'tuple'>


In [13]:
x = [10,20,30]
print(x)
print(type(x))

[10, 20, 30]
<class 'list'>


In [14]:
x = {10,20,30}
print(x)
print(type(x))

{10, 20, 30}
<class 'set'>


In [15]:
x = {'a':20, 'b':30}
print(x)
print(type(x))

{'a': 20, 'b': 30}
<class 'dict'>


In [16]:
# operators in py
a = 5
b= 3
print(a+b)


8


In [17]:
a = 5
b= 3
print(a-b)

2


In [18]:
a = 5
b= 3
print(a*b)

15


In [20]:
a = 5
b= 3
print(a/b)

1.6666666666666667


In [21]:
#modulous
a = 19
b = 3
print(a%b)

1


In [23]:
a = 5
print(a**3)

125


In [25]:
# Built in functions
x = 10
y= 5
expression = 'x+y*2'
result = eval(expression)
print(result)

20


In [26]:
# abs function
a = -10
print(abs(a))

10


In [27]:
#sum function
xyz = [1,2,3,4,5]
total = sum(xyz)
print(total)


15


In [28]:
# pow function
result = pow(285.12,3)
print(result)

23178378.313728


In [30]:
# input function
a = input("pleae enter your age")
print(a)
print(type(a))


pleae enter your age2
2
<class 'str'>


In [31]:
#int function
a = input("pleae enter your age")
print(a)
print(b)
print(type(b))

pleae enter your age3
3
3
<class 'int'>


In [32]:
# str function
abc = 68
print(abc)
print(type(abc))
xyz=str(abc)
print(xyz)
print(type(xyz))

68
<class 'int'>
68
<class 'str'>


In [34]:
# float function
a = input("please enter price")
print(type(a))
b= float(a)
print(b)
print(type(b))

please enter price5050.5
<class 'str'>
5050.5
<class 'float'>


In [37]:
# len function
a ="Hello im a   student"
print(len(a))

20


In [38]:
# sum num in py
num1 = 5.5
num2 = 4.5
total = num1 + num2

print(total)



10.0


In [39]:
# control flow statement
# if statement
age = 18

if age >= 18:
    print("You are an adult.")



You are an adult.


In [51]:
i = 20

if (i > 10):
    print("10 is less than 20")
print ("i am outside the block")


10 is less than 20
i am outside the block


In [52]:
# if else statement
i = 5

if i > 10:
    print("i is greater than 10")
else:
    print("i is 10 or less")



i is 10 or less


In [53]:
# if-elif-else statement
score = 85

if score >= 90:
    print("Grade: A")
elif score >= 80:
    print("Grade: B")
elif score >= 70:
    print("Grade: C")
else:
    print("Grade: F")


Grade: B


In [54]:
# concept of loops
# Runs 3 times (from 0 to 2)
for i in range(3):
    print("Loop number:", i)


Loop number: 0
Loop number: 1
Loop number: 2


In [55]:
countdown = 3

while countdown > 0:
    print(countdown)
    countdown -= 1

print("Blast off!")


3
2
1
Blast off!


In [56]:
# Count from 1 up to (but not including) 6
for i in range(1, 6):
    print(f"Line number {i}")


Line number 1
Line number 2
Line number 3
Line number 4
Line number 5


In [59]:
# break statement
for i in range(10):
  if i == 5:
    break
    print(i)


In [66]:
# cont statement
for i in range(10):
  if i == 5:
    continue
    print(i)
print("Heello")


Heello


In [65]:
# user define functions
def abc():
  print("Hello nepal")
abc()

Hello nepal


In [76]:
# Quick test version: No manual typing required!
for i in range(3):

    name = f"User {i+1}"
    n = 100 + (i * 50)

    bill = n * 5
    print(f"Hi {name}, you need to pay Rs. {bill}")



Hi User 1, you need to pay Rs. 500
Hi User 2, you need to pay Rs. 750
Hi User 3, you need to pay Rs. 1000


In [ ]:
# Argumnets
def describe_pet(animal_type, pet_name):
    print(f"I have a {animal_type} named {pet_name}.")


describe_pet("dog", "Buddy")
describe_pet("Buddy", "dog")


In [77]:
# String in python
single = 'Hello'
double = "World"
multiline = """This is a
multi-line string."""


In [78]:
# Indexing
languages = ["Python", "Java", "C++", "JavaScript"]

print(languages[0])
print(languages[2])


Python
C++


In [79]:
# slicing
text = "Python"

# Get characters from index 0 up to (but excluding) 4
print(text[0:4])   # Output: Pyth

# If you omit the start, it starts from the beginning (0)
print(text[:3])    # Output: Pyt

# If you omit the stop, it goes all the way to the end
print(text[2:])    # Output: thon


Pyth
Pyt
thon


In [81]:
# Check string
message = "Welcome to Python programming!"

if "Python" in message:
    print("Found it!")


if "Java" not in message:
    print("Java is not in the text.")


Found it!
Java is not in the text.


In [ ]:
# .upper() Method
text = "Python 3.x"
upper_text = text.upper()

print(upper_text)
print(text)


In [82]:
# .lower() Method
shouting = "PLEASE STOP SHOUTING!"
quiet = shouting.lower()

print(quiet)


please stop shouting!


In [83]:
# REplace
a = "Hello world"
print(a.replace('H','3'))

3ello world


In [84]:
# String Concatenation
a = "Hello"
b = "world"
print(a+b)

Helloworld


In [ ]:
# List
fruits = ["apple", "banana", "cherry"]
mixed_list = [42, "hello", True, 3.14]
empty_list = []



In [86]:
# Slicing
c = [10,20,30,40,50,60]
print(c[2:5])

[30, 40, 50]


In [87]:
# Tuples
# Create a tuple
my_tuple = ("apple", "banana", "cherry")


print(my_tuple)


('apple', 'banana', 'cherry')


In [89]:
# A tuple containing profile data
user_profile = ("Alice", 28, "programmer")


name, age, profession = user_profile

print(name)
print(age)
print(profession)


Alice
28
programmer


In [90]:
# Dictionary
car = {"brand": "Toyota", "year": 2020}
car["year"] = 2024

car["color"] = "red"

print(car)


{'brand': 'Toyota', 'year': 2024, 'color': 'red'}


In [91]:
# Keys do not use quotes inside the constructor
user = dict(name="Alice", age=25, country="Nepal")

print(user)

{'name': 'Alice', 'age': 25, 'country': 'Nepal'}


In [92]:
# sets
# Creating a set with numbers
my_set = {1, 2, 3, 3, 2}
print(my_set)


empty_set = set()



{1, 2, 3}


In [93]:
# set constructor
numbers_list = [1, 2, 2, 3, 4, 4, 4, 5]

unique_numbers = set(numbers_list)
print(unique_numbers)


{1, 2, 3, 4, 5}


In [ ]:
# Numpy Library

In [94]:
import numpy as np


vector = np.array([1, 2, 3, 4])


matrix = np.array([[1, 2, 3], [4, 5, 6]])

print(matrix.shape)


(2, 3)


In [95]:
import numpy as np
a = [1,2,3,4]
b=np.array([1,2,3,4])
print(a)
print(b)

[1, 2, 3, 4]
[1 2 3 4]


In [96]:
c  = np.zeros(3)
print(c)

[0. 0. 0.]


In [97]:
d = np.ones(4)
print(d)

[1. 1. 1. 1.]


In [98]:
e = np.arange(0,10)
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [100]:
# Multi dimensiona array
arr = np.array([[1,2,3],[3,4,5]])
print(arr)

[[1 2 3]
 [3 4 5]]


In [101]:
import numpy as np

# Create a 5D array with a total of 32 elements (2 * 2 * 2 * 2 * 2 = 32)
array_5d = np.arange(1, 33).reshape(2, 2, 2, 2, 2)

print(array_5d)


[[[[[ 1  2]
    [ 3  4]]

   [[ 5  6]
    [ 7  8]]]


  [[[ 9 10]
    [11 12]]

   [[13 14]
    [15 16]]]]



 [[[[17 18]
    [19 20]]

   [[21 22]
    [23 24]]]


  [[[25 26]
    [27 28]]

   [[29 30]
    [31 32]]]]]


In [ ]:
# Pandas

In [ ]:
import pandas as pd
df = pd.read_csv("")
df


In [ ]:
df.dtypes

In [ ]:
df.describe()

In [ ]:
df.tail(7)

In [ ]:
df[['Name'],'sex','ticket','cabin','Embarked']

In [ ]:
df[df.dytypes[df.dtypes == 'float.64'].index]

In [ ]:
df.columns

In [ ]:
df[['ticket', 'cabin']]

In [ ]:
df[['ticket', 'cabin']][4:17:3]

In [ ]:
df.head()

In [ ]:
df.insert(loc=3,column='food',)